### ISSUE TITLE
Add Pods support

### ISSUE THREAD

**Issue by lightsprint09** [dbsystel/DBNetworkStack#1]

**Comment by lfarah** [comment]
I'd be cool to also add CocoaPods support. I've done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by lightsprint09** [comment]
Done with [1ccdb](https://github.com/dbsystel/DBNetworkStack/commit/1ccdb3a0d36cca85d06b51940db23f5451f63bd0)
