### ISSUE TITLE
Rework NetworkRequestRepresenting

### ISSUE THREAD

**Issue by ch-one** [dbsystel/DBNetworkStack#34]
# Issue:
For the following reasons, we want to try an other approach to represent requests:
* Base URL Key concept is not directly comprehensible
* Not all information about the request is available: `NetworkRequestRepresenting` does not contain the whole URL to perform the request.
* `NetworkRequestRepresenting` can be configured to be invalid. This is not ideal.
  * Issue #31 
  * Issue #32 

# Proposed solution:
We aim for a solution that addresses these points. The proposed solution is to rewrite the `NetworkRequestRepresenting` protocol that its only function is to return a valid `URLRequest`.
* Simplifies usage of `DBNetworkStack` by removing Base URL Key concept (See: #9). An `URLRequest` contains all information about the request
* With an `URLRequest` starting this request should always be possible, which resolves #31 and #32

**Comment by lightsprint09** [comment]
done with #35
