### ISSUE TITLE
Add support for injecting NSMutuableURLRequest

### ISSUE THREAD

**Issue by dennispost** [dbsystel/DBNetworkStack#60]

**Comment by lightsprint09** [comment]
Can you give an example for what reason you need `NSMutuableURLRequest `

**Comment by dennispost** [comment]
My concrete case is based on Network Extensions framework. Especially you can bind an NSMutuableURLRequest to a HotspotHelper command that uses its own TCP connection. 

I can imagine such use cases for VPN and multipath applications too.

**Comment by lightsprint09** [comment]
This can be solved by implementing your own `NetworkServiceProviding` which transforms all `URLRequests` into `NSMutuableURLRequest `. Then you are able to modify & execute them.
